import 'dart:ui';

import 'package:cashless/models/artista.dart';
import 'package:cashless/models/direccion.dart';
import 'package:cashless/models/producto.dart';
import 'package:cashless/models/tienda.dart';

class Statics {
  static String apiUrl = 'https://lakes-feel.herokuapp.com/api';
  //static String apiUrl = 'http://192.168.0.7:3000/api';

  static Map<int, Color> color = {
    50: const Color.fromRGBO(255, 255, 255, .1),
    100: const Color.fromRGBO(255, 255, 255, .2),
    200: const Color.fromRGBO(255, 255, 255, .3),
    300: const Color.fromRGBO(255, 255, 255, .4),
    400: const Color.fromRGBO(255, 255, 255, .5),
    500: const Color.fromRGBO(255, 255, 255, .6),
    600: const Color.fromRGBO(255, 255, 255, .7),
    700: const Color.fromRGBO(255, 255, 255, .8),
    800: const Color.fromRGBO(255, 255, 255, .9),
    900: const Color.fromRGBO(255, 255, 255, 1),
  };

  static List<dynamic> listaRecargas = [
    {"cantidad": 200},
    {"cantidad": 300},
    {"cantidad": 400},
    {"cantidad": 500},
    {"cantidad": 600},
    {"cantidad": 700},
    {"cantidad": 800},
    {"cantidad": 900},
    {"cantidad": 1000},
  ];

  static List<Artista> listaParticipantes = [
    Artista(
        imgUrl: 'assets/images/artistas/chile.png',
        instagram: 'https://www.instagram.com/eduardoelchile/',
        nombre: 'Chile',
        spotify:
            'https://open.spotify.com/artist/0BnmjviyW0BAR2kK67AOPQ?si=O7qqYJgmSOC0O4bfSaaYxQ',
        instagramUserName: 'eduardoelchile'),
    Artista(
        imgUrl: 'assets/images/artistas/shanti.png',
        instagram: 'https://www.instagram.com/shantidj_/',
        nombre: 'Shanti',
        spotify:
            'https://open.spotify.com/artist/2M61yLIBBytyKJvB6saLmt?si=kRYvJUMtQsW5rvIJG_W65Q',
        instagramUserName: 'shantidj'),
    Artista(
        imgUrl: 'assets/images/artistas/to.png',
        instagram: 'https://www.instagram.com/2lionsofficial/',
        nombre: '2Lions',
        spotify:
            'https://open.spotify.com/artist/1TlQDvo1nnM3Oyczb0UFjM?si=tdBPj0qHT_KkNK1BzQnsSQ',
        instagramUserName: '2lionsofficial'),
    Artista(
        imgUrl: 'assets/images/artistas/abril_vega.png',
        instagram: 'https://www.instagram.com/abrilvegamusic/',
        nombre: 'Abril Vega',
        spotify: '',
        instagramUserName: 'abrilvegamusic'),
    Artista(
        imgUrl: 'assets/images/artistas/bryan_tavarez.png',
        instagram: 'https://www.instagram.com/soybrayantavares/',
        nombre: 'Brayan Tavares',
        spotify: '',
        instagramUserName: 'soybrayantavares'),
    Artista(
        imgUrl: 'assets/images/artistas/caro_rivas.png',
        instagram: 'https://www.instagram.com/caro_rivas_18/',
        nombre: 'Caro Rivas',
        spotify: '',
        instagramUserName: 'caro_rivas_18'),
    Artista(
        imgUrl: 'assets/images/artistas/chpe.png',
        instagram: 'https://www.instagram.com/chpe_official/',
        nombre: 'Chpe',
        spotify: '',
        instagramUserName: 'chpe_official'),
    Artista(
        imgUrl: 'assets/images/artistas/don_dany.png',
        instagram: 'https://www.instagram.com/don_dany.mx/',
        nombre: 'Don Dany',
        spotify: '',
        instagramUserName: 'don_dany.mx'),
    Artista(
        imgUrl: 'assets/images/artistas/fakers.png',
        instagram: 'https://www.instagram.com/fakersmusic/',
        nombre: 'Fakers',
        spotify:
            'https://open.spotify.com/artist/1SoCo4hOon1z3JLvEO8Heg?si=8iwCljRdQC6ELgqCwp795w',
        instagramUserName: 'fakersmusic'),
    Artista(
        imgUrl: 'assets/images/artistas/house_tumblr.png',
        instagram: 'https://www.instagram.com/house_tumblr_music_oficial/',
        nombre: 'House & Tumblr',
        spotify:
            'https://open.spotify.com/user/21mql7ueau2lmbx3tzkim7opq?si=5632aef4970b45fa',
        instagramUserName: 'house_tumblr_music_oficial'),
    Artista(
        imgUrl: 'assets/images/artistas/jdez.png',
        instagram: 'https://www.instagram.com/jdez.mx/',
        nombre: 'Jdez',
        spotify: '',
        instagramUserName: 'jdez.mx'),
    Artista(
        imgUrl: 'assets/images/artistas/koude.png',
        instagram: 'https://www.instagram.com/koude_music/',
        nombre: 'Koude',
        spotify:
            'https://open.spotify.com/artist/4nfGTIbp4dKd72NsYhjMcg?si=CaEi8hS9QfydOg3CDK4asQ',
        instagramUserName: 'koude_music'),
    Artista(
        imgUrl: 'assets/images/artistas/jorge_escalante.png',
        instagram: 'https://www.instagram.com/jl.escalante/',
        nombre: 'Jorge Escalante',
        spotify:
            'https://open.spotify.com/artist/3HI4nYJbYBRufLP4zFTIwQ?si=w1qCtq_uTNWGw3ib6stmbQ',
        instagramUserName: 'jl.escalante'),
    Artista(
        imgUrl: 'assets/images/artistas/la_shei.png',
        instagram: 'https://www.instagram.com/lasheimx/',
        nombre: 'La Shei',
        spotify:
            'https://open.spotify.com/artist/5yB5onTa64t5wPrzVH4EkM?si=NLWjxYV7Q1axaKY-c1v1zg',
        instagramUserName: 'lasheimx'),
    Artista(
        imgUrl: 'assets/images/artistas/loretta.png',
        instagram: 'https://www.instagram.com/lorettamaciasdj/',
        nombre: 'Loretta',
        spotify:
            'https://open.spotify.com/user/12165422412?si=6d506f044bbe4087',
        instagramUserName: 'lorettamaciasdj'),
    Artista(
        imgUrl: 'assets/images/artistas/manuel_ridde.png',
        instagram: 'https://www.instagram.com/_manuel_ridde_dj/',
        nombre: 'Manuel Ride',
        spotify: '',
        instagramUserName: '_manuel_ridde_dj'),
    Artista(
        imgUrl: 'assets/images/artistas/neon_de_luz.png',
        instagram: 'https://www.instagram.com/neondeluzmusic/',
        nombre: 'Neon deLuz',
        spotify:
            'https://open.spotify.com/artist/07imWI9ER2YJO1oLccN8wm?si=80uDJ_oUTZys4SK6zUkY-w',
        instagramUserName: 'neondeluzmusic'),
    Artista(
        imgUrl: 'assets/images/artistas/pelon.png',
        instagram: 'https://www.instagram.com/_pelon____/',
        nombre: 'Pelon',
        spotify: '',
        instagramUserName: '_pelon____'),
    Artista(
        imgUrl: 'assets/images/artistas/seneca.png',
        instagram: 'https://www.instagram.com/seneca.mx/',
        nombre: 'Seneca',
        spotify: '',
        instagramUserName: 'seneca.mx'),
    Artista(
        imgUrl: 'assets/images/artistas/rebeld.png',
        instagram: 'https://www.instagram.com/rebeld_music/',
        nombre: 'Rebeld',
        spotify:
            'https://open.spotify.com/artist/5nV4fUZOdiXdQTmCWoCGme?si=yJfrl-xmQ5uYhiSjRi-RlQ',
        instagramUserName: 'rebeld_music'),
    Artista(
        imgUrl: 'assets/images/artistas/st_glez.png',
        instagram: 'https://www.instagram.com/st.glez/',
        nombre: 'St Glez',
        spotify:
            'https://open.spotify.com/artist/0t4NRFAvujuxTENfgUagWa?si=_lsgdvUySa-5V6Szti2XEg',
        instagramUserName: 'st.glez'),
    Artista(
        imgUrl: 'assets/images/artistas/toxic_rabbit.png',
        instagram: 'https://www.instagram.com/toxic_rabbit14/',
        nombre: 'Toxic Rabbit',
        spotify: '',
        instagramUserName: 'toxic_rabbit14'),
    Artista(
        imgUrl: 'assets/images/artistas/traxx.png',
        instagram: 'https://www.instagram.com/traxxdjxxart/',
        nombre: 'Traxx',
        spotify: '',
        instagramUserName: 'traxxdjxxart'),
    Artista(
        imgUrl: 'assets/images/artistas/wild_dog.png',
        instagram: 'https://www.instagram.com/wilddog_la/',
        nombre: 'Wild Dog',
        spotify: '',
        instagramUserName: 'wilddog_la'),
    Artista(
        imgUrl: 'assets/images/artistas/alex_g.png',
        instagram: 'https://instagram.com/alexgonz.mx?igshid=MTIyMzRjYmRlZg==',
        nombre: 'Alex Gonz',
        spotify: '',
        instagramUserName: 'alexgonz.mx'),
    Artista(
        imgUrl: 'assets/images/artistas/diit.png',
        instagram: 'https://instagram.com/diit_music?igshid=MTIyMzRjYmRlZg==',
        nombre: 'Diit',
        spotify:
            'https://open.spotify.com/track/7xFrppTn1vBHd4amB0h5YX?si=KzhbtMOBRvqQ9HLl8UAFjQ',
        instagramUserName: 'diit_music'),
    Artista(
        imgUrl: 'assets/images/artistas/JOAC.png',
        instagram: 'https://instagram.com/djjoac?igshid=MTIyMzRjYmRlZg==',
        nombre: 'Joac',
        spotify: '',
        instagramUserName: 'djjoac'),
    Artista(
        imgUrl: 'assets/images/artistas/marie_fleur.png',
        instagram: 'https://instagram.com/mariefleurdj?igshid=MTIyMzRjYmRlZg==',
        nombre: 'Marie Fleur',
        spotify: '',
        instagramUserName: 'mariefleurdj'),
    Artista(
        imgUrl: 'assets/images/artistas/sheck.png',
        instagram:
            'https://instagram.com/sheckler_music?igshid=MTIyMzRjYmRlZg==',
        nombre: 'Sheckler',
        spotify:
            'https://open.spotify.com/artist/4Uh7G9Zg59cAcNrSA4OvJX?si=yuDP09i4QV687k_HqVYf7A',
        instagramUserName: 'sheckler_music'),
    Artista(
        imgUrl: 'assets/images/artistas/bellaco.png',
        instagram:
            'https://instagram.com/sock.elbellako?igshid=MTIyMzRjYmRlZg==',
        nombre: 'Sock El Bellaco',
        spotify:
            'https://open.spotify.com/artist/7pT3NyHSmtS7tMViD9xJgx?si=c2veXFWDQzWvfWe4DmwdwQ',
        instagramUserName: 'sock.elbellako'),
  ];

  static List<Tienda> tiendas = [
    Tienda(
        fotografias: '',
        inventario: [],
        equipo: [],
        ventas: [],
        nombre: 'Lakes Feel',
        propietario: '',
        disponible: true,
        productos: '',
        aniversario: DateTime.now(),
        direccion: 'direccion',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        uid: '645acc4cd8e275fa5a9be2af',
        horario: Horario(apertura: DateTime.now(), cierre: DateTime.now()),
        coordenadas:
            Coordenadas(id: '', latitud: 0, longitud: 0, lat: 0, lng: 0),
        tiempoEspera: 20,
        online: true,
        puntoVenta: '',
        imagenPerfil: '',
        autoImpresion: true,
        mac: 'mac',
        tiendaRopa: false,
        sugerencia: false,
        promociones: [],
        listaProductos: listaProductoLakesFeel),
    Tienda(
        fotografias: '',
        inventario: [],
        equipo: [],
        ventas: [],
        nombre: 'La Burguesa',
        propietario: '',
        disponible: true,
        productos: '',
        aniversario: DateTime.now(),
        direccion: 'direccion',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        uid: '',
        horario: Horario(apertura: DateTime.now(), cierre: DateTime.now()),
        coordenadas:
            Coordenadas(id: '', latitud: 0, longitud: 0, lat: 0, lng: 0),
        tiempoEspera: 20,
        online: true,
        puntoVenta: '',
        imagenPerfil: '',
        autoImpresion: true,
        mac: 'mac',
        tiendaRopa: false,
        sugerencia: false,
        promociones: [],
        listaProductos: listaBurguesa),
    Tienda(
        fotografias: '',
        inventario: [],
        equipo: [],
        ventas: [],
        nombre: 'Gula La',
        propietario: '',
        disponible: true,
        productos: '',
        aniversario: DateTime.now(),
        direccion: 'direccion',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        uid: '645acc6c77fc0a44a877f5b9',
        horario: Horario(apertura: DateTime.now(), cierre: DateTime.now()),
        coordenadas:
            Coordenadas(id: '', latitud: 0, longitud: 0, lat: 0, lng: 0),
        tiempoEspera: 20,
        online: true,
        puntoVenta: '',
        imagenPerfil: '',
        autoImpresion: true,
        mac: 'mac',
        tiendaRopa: false,
        sugerencia: false,
        promociones: [],
        listaProductos: listaProductoGulaLa),
    Tienda(
        fotografias: '',
        inventario: [],
        equipo: [],
        ventas: [],
        nombre: 'Duros y tostadas el padre',
        propietario: '',
        disponible: true,
        productos: '',
        aniversario: DateTime.now(),
        direccion: 'direccion',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        uid: '645acc7835a572e22b2670d1',
        horario: Horario(apertura: DateTime.now(), cierre: DateTime.now()),
        coordenadas:
            Coordenadas(id: '', latitud: 0, longitud: 0, lat: 0, lng: 0),
        tiempoEspera: 20,
        online: true,
        puntoVenta: '',
        imagenPerfil: '',
        autoImpresion: true,
        mac: 'mac',
        tiendaRopa: false,
        sugerencia: false,
        promociones: [],
        listaProductos: [
          Producto(
              fechaVenta: DateTime.now(),
              id: '6477698efe87b0afd9ad1abe',
              precio: 70,
              nombre: 'Guacamaya',
              descripcion: '',
              descuentoP: 0,
              descuentoC: 0,
              disponible: true,
              tienda: 'Duros y tostadas el padre',
              cantidad: 0,
              sku: 'sku',
              hot: 0,
              extra: 0,
              sugerencia: false,
              imagen: '',
              apartado: true,
              opciones: []),
          Producto(
              fechaVenta: DateTime.now(),
              id: '647769a1dfbd0d1299d378fb',
              precio: 50,
              nombre: '2 tostadas',
              descripcion: '',
              descuentoP: 0,
              descuentoC: 0,
              disponible: true,
              tienda: 'Duros y tostadas el padre',
              cantidad: 0,
              sku: 'sku',
              hot: 0,
              extra: 0,
              sugerencia: false,
              imagen: '',
              apartado: true,
              opciones: []),
          Producto(
              fechaVenta: DateTime.now(),
              id: '647769a7ab0a415ecb691406',
              precio: 60,
              nombre: 'Totopos',
              descripcion: '',
              descuentoP: 0,
              descuentoC: 0,
              disponible: true,
              tienda: 'Duros y tostadas el padre',
              cantidad: 0,
              sku: 'sku',
              hot: 0,
              extra: 0,
              sugerencia: false,
              imagen: '',
              apartado: true,
              opciones: []),
        ]),
    Tienda(
        fotografias: '',
        inventario: [],
        equipo: [],
        ventas: [],
        nombre: 'Pizzas',
        propietario: '',
        disponible: true,
        productos: '',
        aniversario: DateTime.now(),
        direccion: 'direccion',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        uid: '645acc7f83d790b86c747f14',
        horario: Horario(apertura: DateTime.now(), cierre: DateTime.now()),
        coordenadas:
            Coordenadas(id: '', latitud: 0, longitud: 0, lat: 0, lng: 0),
        tiempoEspera: 20,
        online: true,
        puntoVenta: '',
        imagenPerfil: '',
        autoImpresion: true,
        mac: 'mac',
        tiendaRopa: false,
        sugerencia: false,
        promociones: [],
        listaProductos: [
          Producto(
              fechaVenta: DateTime.now(),
              id: '645b444ab5c2677cc6b27b38',
              precio: 35,
              nombre: 'Rebanada Pizza',
              descripcion: '',
              descuentoP: 0,
              descuentoC: 0,
              disponible: true,
              tienda: 'Pizzas',
              cantidad: 0,
              sku: 'sku',
              hot: 0,
              extra: 0,
              sugerencia: false,
              imagen: '',
              apartado: true,
              opciones: []),
          Producto(
              fechaVenta: DateTime.now(),
              id: '647768a355035ffcfdeca153',
              precio: 20,
              nombre: 'Gordita',
              descripcion: '',
              descuentoP: 0,
              descuentoC: 0,
              disponible: true,
              tienda: 'Pizzas',
              cantidad: 0,
              sku: 'sku',
              hot: 0,
              extra: 0,
              sugerencia: false,
              imagen: '',
              apartado: true,
              opciones: []),
          Producto(
              fechaVenta: DateTime.now(),
              id: '647768d25643f17830886337',
              precio: 50,
              nombre: '3 Gordita',
              descripcion: '',
              descuentoP: 0,
              descuentoC: 0,
              disponible: true,
              tienda: 'Pizzas',
              cantidad: 0,
              sku: 'sku',
              hot: 0,
              extra: 0,
              sugerencia: false,
              imagen: '',
              apartado: true,
              opciones: []),
        ]),
  ];

  static List<Producto> listaProdcutosLaBurguesa = [
    Producto(
        fechaVenta: DateTime.now(),
        id: '645b44eed4f0667df8b174cf',
        precio: 100,
        nombre: 'Litros',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
  ];

  static List<Producto> listaProductoLakesFeel = [
    Producto(
        fechaVenta: DateTime.now(),
        id: '645acdd7f553737b8904c655',
        precio: 100,
        nombre: 'Litros',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645acddeabf98d566de111a8',
        precio: 100,
        nombre: '2 Cerveza',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645acde3eede0eb2a3ca54fb',
        precio: 50,
        nombre: 'Bebida Energetica',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645acdec75e1f95c39879ca8',
        precio: 50,
        nombre: 'Agua Mineral 2lt',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645ace004d879c03e242fde2',
        precio: 40,
        nombre: 'Coca Cola 1lt',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645ace09651b34e561d37847',
        precio: 500,
        nombre: 'Entrada general',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645ace1239163aebcc4e21c6',
        precio: 50,
        nombre: 'EcoVaso',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647767a8f896e3832406a49d',
        precio: 1500,
        nombre: 'Mesa VIP',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647767b484bb9a391e63c375',
        precio: 1950,
        nombre: 'Botella Premium',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647767ee87c0d79fc5d9e089',
        precio: 50,
        nombre: 'Botella Agua',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '64776816203330ab6ebb3324',
        precio: 75,
        nombre: 'Cecina',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647768231ebb8f6ba043c42b',
        precio: 90,
        nombre: 'Hielo',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Lakes Feel',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
  ];

  static List<Producto> listaBurguesa = [

    Producto(
        fechaVenta: DateTime.now(),
        id: '647772d2aefaf2add0adddbd',
        precio: 250,
        nombre: 'Combo 1',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '64777309d8ca275abfef3a84',
        precio: 230,
        nombre: 'Combo 2',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647773101c525985a76abdf9',
        precio: 225,
        nombre: 'Combo 3',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '64777316a76da3568e682145',
        precio: 225,
        nombre: 'Combo 4',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '6477731e2f5138d07642585b',
        precio: 235,
        nombre: 'Combo 5',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '6477748fdc8fd26df7cfa315',
        precio: 389,
        nombre: 'Combo Burguesa',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),

    Producto(
        fechaVenta: DateTime.now(),
        id: '6477766aee97390b6634311f',
        precio: 78,
        nombre: 'Papas francesa',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '64777672b038454abd7238c3',
        precio: 88,
        nombre: 'Papas gajo',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '64777679f92b982ee2d177d9',
        precio: 75,
        nombre: 'Aros de cebolla',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647776828bb5e82700fbfc4b',
        precio: 75,
        nombre: 'Nuggets',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '6477768b6b2525ee10034d38',
        precio: 53,
        nombre: 'Hot Dogs',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647776937f542fdaf89f9347',
        precio: 95,
        nombre: 'Dogo Burguesa',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '6477769aa59e3d9541c21741',
        precio: 75,
        nombre: 'Cono de papas',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647776a27c6343ec309b7873',
        precio: 125,
        nombre: 'Alitas/Boneless',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647776cd46fc93efc9d6762f',
        precio: 99,
        nombre: 'Ceviche',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647776d4d8d4a93dbe078012',
        precio: 135,
        nombre: 'Hamburguesa Original',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647776e1216353a714c7a55c',
        precio: 155,
        nombre: 'Hamburguesa Bbq',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647776ef8a6767a8ee188313',
        precio: 135,
        nombre: 'Hamburguesa Pollo Empanizado',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647776f6e20c51aee17f0af6',
        precio: 155,
        nombre: 'Hamburguesa Hawaiana',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '647776fc96f49882d02f59f2',
        precio: 145,
        nombre: 'Smash Burguer',
        descripcion: '',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'La Burguesa',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    



  ];
  static List<Producto> listaProductoGulaLa = [
    Producto(
        fechaVenta: DateTime.now(),
        id: '645b400bd0cf0c8b6e79aeaf',
        precio: 85,
        nombre: 'Envidia',
        descripcion: 'Arrachera',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Gula La',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645b4014dafd19de8688f48a',
        precio: 85,
        nombre: 'Lujuria',
        descripcion: 'Camarones',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Gula La',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645b401cf87789f89b1e4bba',
        precio: 85,
        nombre: 'Soberbia',
        descripcion: 'Vegetariano flor de calabaza/portobello',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Gula La',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645b4028d02ea3b89ee4f38e',
        precio: 85,
        nombre: 'Pecado Mortal',
        descripcion: 'Pastor negro',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Gula La',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645b402ef3049bcd71d06e1f',
        precio: 85,
        nombre: 'Avaricia',
        descripcion: 'Italiano bolognesa, manchego y asadero',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Gula La',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
    Producto(
        fechaVenta: DateTime.now(),
        id: '645b403453b382826843a446',
        precio: 85,
        nombre: 'Ira',
        descripcion: 'Chorizo y queso',
        descuentoP: 0,
        descuentoC: 0,
        disponible: true,
        tienda: 'Gula La',
        cantidad: 0,
        sku: 'sku',
        hot: 0,
        extra: 0,
        sugerencia: false,
        imagen: '',
        apartado: true,
        opciones: []),
  ];
}
